[project]
name = "saveeditor"
version = "0.1.0"
description = "Generic NRBF / BinaryFormatter save editor"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Drenae" }
]
dependencies = [
    "flet>=0.86.5",
    "nrbf==0.1.2",
]

[dependency-groups]
dev = [
    "flet-cli>=0.86.5",
    "flet-desktop>=0.86.5",
    "flet-web>=0.86.5",
    "flet[test]>=0.86.5",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]

[tool.flet]
org = "com.drenae"
product = "SaveEditor"
company = "Drenae"
copyright = "Copyright (C) 2026 Drenae"

[tool.flet.app]
path = "src"
